INSERT INTO T_ACG_CLIENTE (TP_CLIENTE, END_EMAIL, NMR_TELEFONE, DS_SENHA, NMR_CELULAR, DT_CRIADO, DT_ATUALIZADO)VALUES (0, 'gui', '1', 'iyosta', '1', '2023-11-20', '2023-11-21');



INSERT INTO T_ACG_CLIENTE (TP_CLIENTE, END_EMAIL, NMR_TELEFONE, DS_SENHA, NMR_CELULAR, DT_CRIADO, DT_ATUALIZADO) VALUES (0, 'gui', '1', '39FBYe', '1', TO_DATE('2023-11-13', 'YYYY-MM-DD'), TO_DATE('2023-11-13', 'YYYY-MM-DD'));




INSERT INTO T_ACG_CLIENTE (TP_CLIENTE, END_EMAIL, NMR_TELEFONE, DS_SENHA, NMR_CELULAR, DT_CRIADO, DT_ATUALIZADO) VALUES (0, 'guafigbjnakfngokdasfnoisamfdsaok', '11', 'it5wkD', '11', TO_DATE('2023-11-13', 'YYYY-MM-DD'), TO_DATE('2023-11-13', 'YYYY-MM-DD'));

select * from T_ACG_CLIENTE_juridico;

select * from T_ACG_CLIENTE_fisico;

select * from T_ACG_CLIENTE;

SELECT * FROM T_ACG_TIPO_GUINCHO;

-- Exemplo 1
INSERT INTO T_ACG_TIPO_GUINCHO (NM_TIPO, CPCD_CARGA, MAX_ALTURA_ELEVACAO, MAX_COMPRIMENTO_CABO, NMR_CABOS, PESO_TOTAL, DT_CRIADO, DT_ATUALIZADO)
VALUES ('Tipo A', 5000, 15.5, 30.0, 1, 2000, SYSDATE, SYSDATE);

-- Exemplo 2
INSERT INTO T_ACG_TIPO_GUINCHO (NM_TIPO, CPCD_CARGA, MAX_ALTURA_ELEVACAO, MAX_COMPRIMENTO_CABO, NMR_CABOS, PESO_TOTAL, DT_CRIADO, DT_ATUALIZADO)
VALUES ('Tipo B', 7000, 20.0, 35.0, 2, 3000, SYSDATE, SYSDATE);

-- Exemplo 3
INSERT INTO T_ACG_TIPO_GUINCHO (NM_TIPO, CPCD_CARGA, MAX_ALTURA_ELEVACAO, MAX_COMPRIMENTO_CABO, NMR_CABOS, PESO_TOTAL, DT_CRIADO, DT_ATUALIZADO)
VALUES ('Tipo C', 10000, 25.0, 40.0, 3, 4000, SYSDATE, SYSDATE);

SELECT * FROM T_ACG_MOTORISTAs;
COMMIT;
